FROM node:18-alpine

WORKDIR /app

COPY ./package*.json /app/

RUN npm install
RUN npm install @nuxt/test-utils vitest --save-dev

COPY . .

EXPOSE 3000
EXPOSE 24678

ENV PATH ./node_modules/.bin/:$PATH